BasicDemo/force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasicDemo/force-app/main/default/objects/Developer__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasicDemo/force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasicDemo/force-app/main/default/objects/Equipment__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Developer</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

BasicDemo/force-app/main/default/objects/Equipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Cable</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Mouse</fullName>
            </value>
            <value>
                <fullName>Keyboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasicDemo/force-app/main/default/objects/Equipment__c/fields/Used_Since__c.field-meta.xml
<CustomField>
    <fullName>Used_Since__c</fullName>
    <label>Used Since</label>
    <type>Date</type>
</CustomField>

BasicDemo/force-app/main/default/classes/DeveloperTriggerHandler.cls
public class DeveloperTriggerHandler {
	
    public static void createEquipmentLevelUp(Map<Id,Developer__c> developerOldMap, List<Developer__c> developerList, Boolean inserted){
        List<Developer__c> levelUpDevList = null;
        if(inserted){
            levelUpDevList = developerList;
        }
        else{
            levelUpDevList = new List<Developer__c>();
            for(Developer__c dev : developerList){
                if(dev.Level__c != developerOldMap.get(dev.Id).Level__c){
                    levelUpDevList.add(dev);
                }
            }
        }
        List<Equipment__c> equipmentList = new List<Equipment__c>();
        for(Developer__c dev : levelUpDevList){
            if(dev.Level__c != '1'){
                Equipment__c eqp = new Equipment__c(Name = dev.Name + '_', Used_Since__c = Date.today(), Developer__c = dev.Id);
                switch on dev.Level__c {
                    when '2'{
                        eqp.Name += 'Mouse';
                        eqp.Type__c = 'Mouse'; 
                    }
                    when '3'{
                        eqp.Name += 'Keyboard';
                        eqp.Type__c = 'Keyboard';
                    }
                    when '4'{
                        eqp.Name += 'Monitor1';
                        eqp.Type__c = 'Monitor';
                    }
                    when '5'{
                        eqp.Name += 'Monitor2';
                        eqp.Type__c = 'Monitor';
                    }
                    when '6'{
                        eqp.Name += 'Laptop2';
                        eqp.Type__c = 'Laptop';
                    }
                    when else{}
                }
            	equipmentList.add(eqp);
            }
        }
        try{
            insert equipmentList;
        }
        catch(Exception se){
            System.debug('Error during equipment insert: ' + se.getMessage() + ' ' + se.getCause() + ' ' + se.getLineNumber() + ' ' + se.getStackTraceString());
        }
    }
}